### ISSUE TITLE
how can I get touch sensor topic

### ISSUE THREAD

**Issue by k-okada** [ros-naoqi/pepper_robot#10]
It seems the pepper robot has multiple touch sensors on head and arms, how can we get this as ros topic?

**Comment by kochigami** [comment]
I could understand how `ALTouch` proxy deals with touch related topics, but I couldn't know how to add codes to new `naoqi_driver`.

Touch data are published as `events` in NAOqi.
`ALMemoryProxy::subscribeToEvent(event name, callbackModule, callback Method(= callback function))` starts raising event.
`ALMemoryProxy::unsubscribeToEvent(event name, callbackModule)` stops rasing event.

When event is subscribed, sensor data are stored and topic is published in callback function. 
Unfortunately, I haven't found these functions in codes yet...

Useful event names:

```
Bumpers:
RightBumperPressed
LeftBumperPressed
BackBumperPressed (it is not described in documentation, but I could use it before)

Head Sensors:
FrontTactilTouched
MiddleTactileTouched
RearTactileTouched

Hand Sensors:
HandRightBackTouched
HandRightLeftTouched
HandRightRightTouched
HandLeftBackTouched
HandRightLeftTouched
HandRightRightTouched
```

In addition, I think some msgs in `naoqi_bridge_msgs` are required to modify or create:
1. Bumper.msg -> add back=2 (for Pepper)
2. add `HandTouch.msg` 

Referenced documentation: NAOqi 2.3 documentation ALTouch, python code `nao_apps/nodes/nao_tactile.py`

**Comment by k-okada** [comment]
I'm working on this issue at https://github.com/ros-naoqi/naoqi_driver/pull/48, but unfortunatelly I have trouble reading data....

**Comment by suryaambrose** [comment]
I think this has been partially solved by https://github.com/ros-naoqi/naoqi_driver/pull/49 and is about to be totally solved by https://github.com/ros-naoqi/naoqi_driver/pull/63 right ?

**Comment by victorpaleologue** [comment]
I think we're good.
