### ISSUE TITLE
Reference frame for /cmd_vel?

### ISSUE THREAD

**Issue by jokla** [ros-naoqi/pepper_robot#24]
Hi!

Just a simple question, to which frame the velocities applied using the topic /cmd_vel  are referred?
I saw in the driver that is used the function `ALMotionProxy::move()`, so the velocites are expressed in the `FRAME_ROBOT`. Does it correspond to the ROS tf frame `/base_footprint`?

Thanks!

**Comment by mikaelarguedas** [comment]
Hi,

I think that the robot_frame is indeed supposed to correspond to `/base_footrpint`. (c.f. [Aldebaran frame definition](http://doc.aldebaran.com/2-1/naoqi/motion/control-cartesian.html#motion-effectors-space)). I can't say for sure that those two frames will be strictly equivalent on all robots (especially for bipedal robots where base_footprint is the projection of base link on the ground). But if they're not strictly equivalent it should be close enough for most applications.

Hope this helps,

**Comment by jokla** [comment]
Thanks!
