### ISSUE TITLE
Error in pepper_bringup perception 

### ISSUE THREAD

**Issue by fspindle** [ros-naoqi/pepper_robot#30]
I can't figure out the following error when launching pepper_full.launch

```
$ roslaunch pepper_bringup pepper_full.launch
roslaunch file contains multiple nodes named [/pepper_robot/camera/rectify_color].
Please check all <node> 'name' attributes to make sure they are unique.
Also check that $(anon id) use different ids.
The traceback for the exception was written to the log file
```

**Comment by furushchev** [comment]
@fspindle Hi, it needs the latest version of `rgbd_launch` package. (c.f. https://github.com/ros-drivers/rgbd_launch/pull/28 )
Could you please print the version of `rgbd_launch`?

``` bash
$ rosversion rgbd_launch
```

And if it is former than `2.1.3`, please upgrade.

**Comment by fspindle** [comment]
Ok thanks, I have 2.1.1

**Comment by furushchev** [comment]
@fspindle Does it work after upgrading `rgbd_launch`? If you still have a problem, please ask here.
If not, please close this issue.

**Comment by fspindle** [comment]
Yes it works. Thanks
