### ISSUE TITLE
CameraTop "overexposure" over time

### ISSUE THREAD

**Issue by kkonen** [ros-naoqi/pepper_robot#41]
The videostream of the headcamera looks "overexposed". 
First it occured after running for about 30 minutes and was gone after a restart.
Now it happens permanently and directly after booting pepper.
See picture.
![pepper_front_camera_malfunction](https://cloud.githubusercontent.com/assets/27768460/25535488/8a9e14e4-2c37-11e7-8b1b-bd2cfddebc4d.png)
Has anyone else experienced this problem, or could this be a camera malfunction of our pepper model?

**Comment by Karsten1987** [comment]
Given that you closed this issue, could you report whether you solved that problem? It might be helpful for other people coming here by search engines.

**Comment by kkonen** [comment]
We decreased the gain, brightness, contrast and saturation default values inside the camera launch file (see our fork for detailed values). This is not the real fix for the problem, but now we get camera pictures we can work with.
