### ISSUE TITLE
Can't visualize Pepper's PointCloud using PCL viewer

### ISSUE THREAD

**Issue by metalaman** [ros-naoqi/pepper_robot#46]
I have written a piece of code which subscribes to my Pepper's depth_registered/points topic, converts the Sensor::msg object to pcl::PointCloud using pcl::fromROSMsg(), when I try to visualize the pcl point cloud I get the following output,
![screenshot from 2018-02-15 19-33-36](https://user-images.githubusercontent.com/8245954/36266813-6ae61c62-1298-11e8-8183-cfcf27c8a51a.png)

I'm able to see the pointcloud on RViZ.
I've tried converting the Sensor::msg PointCloud2 object to both `pcl::PointCloud<pcl::PointXYZRGB>` and `pcl::PointCloud<pcl::PointXYZ>`, gives the same output.

ROS Kinetic
Ubuntu 16.04
Any help?

**Comment by metalaman** [comment]
It's a PCL issue, was able to see it using pcl_viewer and pcd file.

**Comment by daniel-s-ingram** [comment]
@metalaman,  I was having this issue for a while too until I found out what you're seeing is just the three axes zoomed in. Use your mouse wheel to scroll out and you'll see your scene.
