### ISSUE TITLE
Melodic issues 

### ISSUE THREAD

**Issue by redsIng** [ros-naoqi/pepper_robot#58]
We are trying to use this repository in ros melodic. What are the issues that we could find?

**Comment by mbusy** [comment]
Hi, since this repo is not really maintained anymore, I can't give you a definitive answer, but this repo should be compatible with melodic

**Comment by redsIng** [comment]
Thanks, I close this question. We are trying to develop some functionalities on this robot but currently we are encountering a lot of issue with the navigation stack and all the building procedures. We had to fix a lot of error/warnings and we had to avoid to use some functionalities.
This robot is awesome, aesthetically.
