### ISSUE TITLE
laser coordinates is not correct

### ISSUE THREAD

**Issue by k-okada** [ros-naoqi/pepper_robot#9]
It seems origin or lasers is not correct, this should be 10-20cm above ground. Where can I find this specification?

![screenshot from 2015-10-01 19 54 42](https://cloud.githubusercontent.com/assets/493276/10219202/d5da471e-6877-11e5-8635-dabc3383096d.png)

**Comment by Karsten1987** [comment]
As far as I know they are correct (except 2cm of height) since the values which are captured by the camera are pre-processed by NAOqi and projected on the floor.

**Comment by k-okada** [comment]
Ok, thanks
